server:
  port: 8081

spring:
  datasource:
    driverClassName: ${jdbc.driverClassName}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    hikari:
      #连接池
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间,默认60000（10分钟）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间0表示永久存活默认180000（30分钟）
      max-lifetime: 180000
      #连接超过时间(30秒)
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #devtools:
    #restart:
      #热部署时排除哪些资源
      #exclude: jdbc.properties

#mybatisPlus配置
mybatis-plus:
  #配置mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  #配置mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.kawainekosann.server.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false

logging:
  level:
    com.kawainekosann.server.mapper: debug


yaml:
  level:
    str: 字符串不需要双引号
    num: 666
    Dnum: 666.88
    birth: 2000/12/2 12:20:12
#    list: [one,two,three]
    list:
      - one
      - two
      - three
#    set: [1,2,3]
    set:
      - 1
      - 2
      - 3
#    map: {key1: value1,key2: value2}
    map:
      key1: value1
      key2: value2
    users:
      - username: liu
        password: 1
      - username: liu2
        password: 2

yaml2:
  level:
    school:
      name: ss
    str: 字符串不需要双引号7
    num: 777
    Dnum: 7666.88
    birth: 2000/12/7 12:20:12
    #    list: [one,two,three]
    list:
      - one1
      - two1
      - three1
    #    set: [1,2,3]
    set:
      - 11
      - 21
      - 31
    #    map: {key1: value1,key2: value2}
    map:
      key1: value11
      key2: value21
    users:
      - username: liu1
        password: 11
      - username: liu21
        password: 21



